spring.application.name=login-cookie

# activated profile
spring.profiles.active=dev

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Debug
logging.level.org.springframework.security=DEBUG

jwt.secret=7a5487f01940a0d305067edc5db8bc970b8d93ccb34672c93d59ddffa848ada3
